services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - site-data:/var/www/html:ro
      - pag-professores:/var/www/profs:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/dhparam:/etc/nginx/dhparam
      - ./certbot/webroot:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: unless-stopped
    depends_on:
      - certbot
      - ssh
      - php

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/webroot:/var/www/certbot
    entrypoint: /bin/sh -c
    command: >
      "trap exit TERM;
       while :; do
         certbot renew --webroot -w /var/www/certbot --quiet
         sleep 12h & wait $${!};
       done"

  ssh:
    build: ./ssh
    ports:
      - "2264:22"
    volumes:
      - site-data:/home/deployer/site
    restart: unless-stopped

  php:
    build: ./php
    volumes:
      - pag-professores:/var/www/profs
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  site-data:
  pag-professores:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=novailha.dcc.ufrj.br,nolock,soft,rw"
      device: ":/home/cluster/usuarios/professores"

