services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - site-data:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - ssh

  ssh:
    build: ./ssh
    ports:
      - "2264:22"
    volumes:
      - site-data:/home/deployer/site
    restart: unless-stopped

volumes:
  site-data:

