services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - site-data:/var/www/html:ro
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    restart: unless-stopped

  ssh:
    build: ./ssh
    ports:
      - "2264:22"
    volumes:
      - site-data:/home/deployer/site
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: |
      /bin/sh -c '
        if [ ! -d "/etc/letsencrypt/live/ic.atr.rio.br" ]; then
          certbot certonly --webroot -w /var/www/certbot \
            --email supervisao@ic.ufrj.br \
            --agree-tos --no-eff-email \
            -d ic.atr.rio.br;
        fi
        trap exit TERM;
        while :; do
          certbot renew --webroot -w /var/www/certbot --quiet;
          sleep 12h & wait $!;
        done
      '
    restart: unless-stopped
volumes:
  site-data:

