services:
  nginx:
    build: ./nginx
    ports:
      - "8064:80"
    volumes:
      - site-data:/var/www/html:ro
    restart: unless-stopped

  ssh:
    build: ./ssh
    ports:
      - "2264:22"
    volumes:
      - site-data:/home/deployer/site
    restart: unless-stopped
volumes:
  site-data:

